# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renren_fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: DTMKlxj199866
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: localhost
    port: 6379

  shiro-redis:
    enabled: true
    redis-manager:
      host: 127.0.0.1:6379

#配置token生成策略
audience:
  clientId: 071bVwq02GvGxT06Gsp02SoPq02bVwqm
  base64Secret: VDk4ZjSiY2Q0TjIxZDM3g9FhZGU0ZTgzQjYyM2I0KjP=
  name: restapiuser
  expiresSecond: 120

wx:
  appId: wxd01d43a7ec84aa47
  secret: 91f43f64f19f476b2301166e5e9ca23e